<?php
$this->headLink()
    ->prependStylesheet('/css/styles.css');
$this->inlineScript();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?=$this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body class="app">
<div class="app-content">
    <main class="container">
        <?=$this->content?>
    </main>
</div>

<footer class="app-footer">
    <div class="container">
        <hr />
        <p>
            &copy; <?=date('Y')?> <a href="https://matthewsetter.com">Matthew Setter</a>.
        </p>
    </div>
</footer>

<?=$this->inlineScript()?>
</body>
</html>
